Feature/FA-39. Added Dockerfile wordpress and rewrote Ci.yaml
SoftTeco/training-mv pull request #9
Opened 2023-03-31 15:52 UTC by isostheneia94

2023-04-05 10:35 UTC, skrivopishin requested changes
Please view the comments and fix them

2023-04-05 10:35 UTC, skrivopishin commented on .github/actions/ghcr-prune-3.py
> +    #else:
it's better to keep GITHUB_TOKEN as environment variable
it would be easier to use it in actions

2023-04-05 10:35 UTC, skrivopishin commented on .github/actions/ghcr-prune-3.py
> +        # prune old tagged images if requested
extra lines should be deleted or should be implemented as optional functionality

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +    #runs-on: ubuntu-latest
do not need to comment, should be replaced

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +
what for all of this?

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +    #runs-on: ubuntu-latest
no need to keep comments

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +#--------------------------------------------------
should remain

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +#--------------------------------------------------
can be executed as separate step before build

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +    - uses: actions/checkout@v3
all steps should have name
check how it's done above

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +      run: docker build --file Dockerfile --tag ghcr.io/${{ needs.pre_build.outputs.output_owner_lc }}/wordpress:${{ needs.pre_build.outputs.output_tag }} .
Dockerfile is default file for build

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +        uses: ASzc/change-string-case-action@v5
owner should be same organization

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +        uses: ASzc/change-string-case-action@v5
and if you need to make it lowercase, do not use custom step, bash is fine enough

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +      run: docker push ghcr.io/${{ needs.pre_build.outputs.output_owner_lc }}/wordpress:${{ needs.pre_build.outputs.output_tag }}
no need to separate into jobs
build and push can be just steps

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +      run: ./ghcr-prune-3.py --container wordpress --number 10 --token ${{ secrets.GITHUB_TOKEN }}
name of jobs should be short, for example this one can be called "cleanup"

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +      run: ./ghcr-prune-3.py --container wordpress --number 10 --token ${{ secrets.GITHUB_TOKEN }}
same thing about steps

2023-04-05 10:35 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +        severity: 'CRITICAL,HIGH'
security scan should be done before push as a step

2023-04-05 10:35 UTC, skrivopishin commented on wordpress/Dockerfile
> +LABEL maintainer="Max-test1"
maintainer should be normal name, or should be absent

2023-04-05 10:35 UTC, skrivopishin commented on wordpress/Dockerfile
> +COPY wordpress_Dockerfile_folder/functions.php /var/www/html/wp-includes/
wordpress_Dockerfile_folder - bad name
for plugins you can create folder called just plugins, for example "root/wordpress/plugins"
for includes - the same
etc.

2023-04-06 11:04 UTC, isostheneia94 commented
Fixed all remarks

2023-04-06 11:20 UTC, skrivopishin requested changes

2023-04-06 11:20 UTC, skrivopishin commented on .github/actions/ghcr-prune-3.py
> +__author__ = "Max VeRBiTSKiy"
should be "Maxim Verbitskiy"

2023-04-06 11:20 UTC, skrivopishin commented on .github/actions/ghcr-prune-3.py
> +    token = args.token
token variable should be possible to get from GITHUB_TOKEN environment variable

2023-04-06 11:20 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +  build_with_secure:
call this just as "build"

2023-04-06 11:20 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +  build_semantic:
call this as "generate_version"

2023-04-06 11:20 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +      run: echo "OWNER_LOWERCASE=$(./owner_lowercase.sh ${{ github.repository_owner }})" >> $GITHUB_ENV
just use command like:
`echo "$a" | awk '{print tolower($0)}'`

2023-04-06 11:20 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u softteco --password-stdin
github.repository_owner can be use as a username

2023-04-12 09:29 UTC, skrivopishin commented on .github/workflows/ci.yaml
> +        severity: 'CRITICAL,HIGH'
1. для ENV переменных сохраняй uppercase
2. для каждого таска порядок: сначала name, потом uses или shell, если используется run, в конце working-directory

```yaml
- name: WP Docker Image Build
  shell: bash
  run: docker build --tag ghcr.io/${{ env.OWNER_LOWERCASE }}/wordpress:${{ env.RELEASE_VERSION }} .
  working-directory: wordpress

- name: WP Image Trivy Secure
  uses: aquasecurity/trivy-action@master
  with:
    image-ref: "ghcr.io/${{ env.OWNER_LOWERCASE }}/wordpress:${{ env.RELEASE_VERSION }}"
    format: "table"
    ignore-unfixed: true
    vuln-type: "os,library"
    severity: "CRITICAL,HIGH"
```

2023-04-12 13:57 UTC, skrivopishin approved these changes

2023-04-13 07:40 UTC, merged